// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WasherProfilesColumns holds the columns for the "washer_profiles" table.
	WasherProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "service_details", Type: field.TypeString, Nullable: true},
		{Name: "availability", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_washer_profile", Type: field.TypeUUID, Unique: true},
	}
	// WasherProfilesTable holds the schema information for the "washer_profiles" table.
	WasherProfilesTable = &schema.Table{
		Name:       "washer_profiles",
		Columns:    WasherProfilesColumns,
		PrimaryKey: []*schema.Column{WasherProfilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "washer_profiles_users_washer_profile",
				Columns:    []*schema.Column{WasherProfilesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		WasherProfilesTable,
	}
)

func init() {
	WasherProfilesTable.ForeignKeys[0].RefTable = UsersTable
}
