// Code generated by ent, DO NOT EDIT.

package ent

import (
	"the-car-wash-directory/ent/schema"
	"the-car-wash-directory/ent/user"
	"the-car-wash-directory/ent/washerprofile"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[1].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[2].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	washerprofileFields := schema.WasherProfile{}.Fields()
	_ = washerprofileFields
	// washerprofileDescCreatedAt is the schema descriptor for created_at field.
	washerprofileDescCreatedAt := washerprofileFields[3].Descriptor()
	// washerprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	washerprofile.DefaultCreatedAt = washerprofileDescCreatedAt.Default.(func() time.Time)
	// washerprofileDescUpdatedAt is the schema descriptor for updated_at field.
	washerprofileDescUpdatedAt := washerprofileFields[4].Descriptor()
	// washerprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	washerprofile.DefaultUpdatedAt = washerprofileDescUpdatedAt.Default.(func() time.Time)
	// washerprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	washerprofile.UpdateDefaultUpdatedAt = washerprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// washerprofileDescID is the schema descriptor for id field.
	washerprofileDescID := washerprofileFields[0].Descriptor()
	// washerprofile.DefaultID holds the default value on creation for the id field.
	washerprofile.DefaultID = washerprofileDescID.Default.(func() uuid.UUID)
}
