// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"the-car-wash-directory/ent/predicate"
	"the-car-wash-directory/ent/user"
	"the-car-wash-directory/ent/washerprofile"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WasherProfileQuery is the builder for querying WasherProfile entities.
type WasherProfileQuery struct {
	config
	ctx        *QueryContext
	order      []washerprofile.OrderOption
	inters     []Interceptor
	predicates []predicate.WasherProfile
	withOwner  *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WasherProfileQuery builder.
func (wpq *WasherProfileQuery) Where(ps ...predicate.WasherProfile) *WasherProfileQuery {
	wpq.predicates = append(wpq.predicates, ps...)
	return wpq
}

// Limit the number of records to be returned by this query.
func (wpq *WasherProfileQuery) Limit(limit int) *WasherProfileQuery {
	wpq.ctx.Limit = &limit
	return wpq
}

// Offset to start from.
func (wpq *WasherProfileQuery) Offset(offset int) *WasherProfileQuery {
	wpq.ctx.Offset = &offset
	return wpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wpq *WasherProfileQuery) Unique(unique bool) *WasherProfileQuery {
	wpq.ctx.Unique = &unique
	return wpq
}

// Order specifies how the records should be ordered.
func (wpq *WasherProfileQuery) Order(o ...washerprofile.OrderOption) *WasherProfileQuery {
	wpq.order = append(wpq.order, o...)
	return wpq
}

// QueryOwner chains the current query on the "owner" edge.
func (wpq *WasherProfileQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: wpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(washerprofile.Table, washerprofile.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, washerprofile.OwnerTable, washerprofile.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(wpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WasherProfile entity from the query.
// Returns a *NotFoundError when no WasherProfile was found.
func (wpq *WasherProfileQuery) First(ctx context.Context) (*WasherProfile, error) {
	nodes, err := wpq.Limit(1).All(setContextOp(ctx, wpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{washerprofile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wpq *WasherProfileQuery) FirstX(ctx context.Context) *WasherProfile {
	node, err := wpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WasherProfile ID from the query.
// Returns a *NotFoundError when no WasherProfile ID was found.
func (wpq *WasherProfileQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wpq.Limit(1).IDs(setContextOp(ctx, wpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{washerprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wpq *WasherProfileQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := wpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WasherProfile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WasherProfile entity is found.
// Returns a *NotFoundError when no WasherProfile entities are found.
func (wpq *WasherProfileQuery) Only(ctx context.Context) (*WasherProfile, error) {
	nodes, err := wpq.Limit(2).All(setContextOp(ctx, wpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{washerprofile.Label}
	default:
		return nil, &NotSingularError{washerprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wpq *WasherProfileQuery) OnlyX(ctx context.Context) *WasherProfile {
	node, err := wpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WasherProfile ID in the query.
// Returns a *NotSingularError when more than one WasherProfile ID is found.
// Returns a *NotFoundError when no entities are found.
func (wpq *WasherProfileQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wpq.Limit(2).IDs(setContextOp(ctx, wpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{washerprofile.Label}
	default:
		err = &NotSingularError{washerprofile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wpq *WasherProfileQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := wpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WasherProfiles.
func (wpq *WasherProfileQuery) All(ctx context.Context) ([]*WasherProfile, error) {
	ctx = setContextOp(ctx, wpq.ctx, ent.OpQueryAll)
	if err := wpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WasherProfile, *WasherProfileQuery]()
	return withInterceptors[[]*WasherProfile](ctx, wpq, qr, wpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wpq *WasherProfileQuery) AllX(ctx context.Context) []*WasherProfile {
	nodes, err := wpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WasherProfile IDs.
func (wpq *WasherProfileQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if wpq.ctx.Unique == nil && wpq.path != nil {
		wpq.Unique(true)
	}
	ctx = setContextOp(ctx, wpq.ctx, ent.OpQueryIDs)
	if err = wpq.Select(washerprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wpq *WasherProfileQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := wpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wpq *WasherProfileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wpq.ctx, ent.OpQueryCount)
	if err := wpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wpq, querierCount[*WasherProfileQuery](), wpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wpq *WasherProfileQuery) CountX(ctx context.Context) int {
	count, err := wpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wpq *WasherProfileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wpq.ctx, ent.OpQueryExist)
	switch _, err := wpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wpq *WasherProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := wpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WasherProfileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wpq *WasherProfileQuery) Clone() *WasherProfileQuery {
	if wpq == nil {
		return nil
	}
	return &WasherProfileQuery{
		config:     wpq.config,
		ctx:        wpq.ctx.Clone(),
		order:      append([]washerprofile.OrderOption{}, wpq.order...),
		inters:     append([]Interceptor{}, wpq.inters...),
		predicates: append([]predicate.WasherProfile{}, wpq.predicates...),
		withOwner:  wpq.withOwner.Clone(),
		// clone intermediate query.
		sql:  wpq.sql.Clone(),
		path: wpq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (wpq *WasherProfileQuery) WithOwner(opts ...func(*UserQuery)) *WasherProfileQuery {
	query := (&UserClient{config: wpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wpq.withOwner = query
	return wpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ServiceDetails string `json:"service_details,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WasherProfile.Query().
//		GroupBy(washerprofile.FieldServiceDetails).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wpq *WasherProfileQuery) GroupBy(field string, fields ...string) *WasherProfileGroupBy {
	wpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WasherProfileGroupBy{build: wpq}
	grbuild.flds = &wpq.ctx.Fields
	grbuild.label = washerprofile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ServiceDetails string `json:"service_details,omitempty"`
//	}
//
//	client.WasherProfile.Query().
//		Select(washerprofile.FieldServiceDetails).
//		Scan(ctx, &v)
func (wpq *WasherProfileQuery) Select(fields ...string) *WasherProfileSelect {
	wpq.ctx.Fields = append(wpq.ctx.Fields, fields...)
	sbuild := &WasherProfileSelect{WasherProfileQuery: wpq}
	sbuild.label = washerprofile.Label
	sbuild.flds, sbuild.scan = &wpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WasherProfileSelect configured with the given aggregations.
func (wpq *WasherProfileQuery) Aggregate(fns ...AggregateFunc) *WasherProfileSelect {
	return wpq.Select().Aggregate(fns...)
}

func (wpq *WasherProfileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wpq); err != nil {
				return err
			}
		}
	}
	for _, f := range wpq.ctx.Fields {
		if !washerprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wpq.path != nil {
		prev, err := wpq.path(ctx)
		if err != nil {
			return err
		}
		wpq.sql = prev
	}
	return nil
}

func (wpq *WasherProfileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WasherProfile, error) {
	var (
		nodes       = []*WasherProfile{}
		withFKs     = wpq.withFKs
		_spec       = wpq.querySpec()
		loadedTypes = [1]bool{
			wpq.withOwner != nil,
		}
	)
	if wpq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, washerprofile.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WasherProfile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WasherProfile{config: wpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wpq.withOwner; query != nil {
		if err := wpq.loadOwner(ctx, query, nodes, nil,
			func(n *WasherProfile, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wpq *WasherProfileQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*WasherProfile, init func(*WasherProfile), assign func(*WasherProfile, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*WasherProfile)
	for i := range nodes {
		if nodes[i].user_washer_profile == nil {
			continue
		}
		fk := *nodes[i].user_washer_profile
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_washer_profile" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (wpq *WasherProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wpq.querySpec()
	_spec.Node.Columns = wpq.ctx.Fields
	if len(wpq.ctx.Fields) > 0 {
		_spec.Unique = wpq.ctx.Unique != nil && *wpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wpq.driver, _spec)
}

func (wpq *WasherProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(washerprofile.Table, washerprofile.Columns, sqlgraph.NewFieldSpec(washerprofile.FieldID, field.TypeUUID))
	_spec.From = wpq.sql
	if unique := wpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wpq.path != nil {
		_spec.Unique = true
	}
	if fields := wpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, washerprofile.FieldID)
		for i := range fields {
			if fields[i] != washerprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wpq *WasherProfileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wpq.driver.Dialect())
	t1 := builder.Table(washerprofile.Table)
	columns := wpq.ctx.Fields
	if len(columns) == 0 {
		columns = washerprofile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wpq.sql != nil {
		selector = wpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wpq.ctx.Unique != nil && *wpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wpq.predicates {
		p(selector)
	}
	for _, p := range wpq.order {
		p(selector)
	}
	if offset := wpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WasherProfileGroupBy is the group-by builder for WasherProfile entities.
type WasherProfileGroupBy struct {
	selector
	build *WasherProfileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wpgb *WasherProfileGroupBy) Aggregate(fns ...AggregateFunc) *WasherProfileGroupBy {
	wpgb.fns = append(wpgb.fns, fns...)
	return wpgb
}

// Scan applies the selector query and scans the result into the given value.
func (wpgb *WasherProfileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wpgb.build.ctx, ent.OpQueryGroupBy)
	if err := wpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WasherProfileQuery, *WasherProfileGroupBy](ctx, wpgb.build, wpgb, wpgb.build.inters, v)
}

func (wpgb *WasherProfileGroupBy) sqlScan(ctx context.Context, root *WasherProfileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wpgb.fns))
	for _, fn := range wpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wpgb.flds)+len(wpgb.fns))
		for _, f := range *wpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WasherProfileSelect is the builder for selecting fields of WasherProfile entities.
type WasherProfileSelect struct {
	*WasherProfileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wps *WasherProfileSelect) Aggregate(fns ...AggregateFunc) *WasherProfileSelect {
	wps.fns = append(wps.fns, fns...)
	return wps
}

// Scan applies the selector query and scans the result into the given value.
func (wps *WasherProfileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wps.ctx, ent.OpQuerySelect)
	if err := wps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WasherProfileQuery, *WasherProfileSelect](ctx, wps.WasherProfileQuery, wps, wps.inters, v)
}

func (wps *WasherProfileSelect) sqlScan(ctx context.Context, root *WasherProfileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wps.fns))
	for _, fn := range wps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
