// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"the-car-wash-directory/ent/predicate"
	"the-car-wash-directory/ent/washerprofile"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WasherProfileDelete is the builder for deleting a WasherProfile entity.
type WasherProfileDelete struct {
	config
	hooks    []Hook
	mutation *WasherProfileMutation
}

// Where appends a list predicates to the WasherProfileDelete builder.
func (wpd *WasherProfileDelete) Where(ps ...predicate.WasherProfile) *WasherProfileDelete {
	wpd.mutation.Where(ps...)
	return wpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wpd *WasherProfileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wpd.sqlExec, wpd.mutation, wpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wpd *WasherProfileDelete) ExecX(ctx context.Context) int {
	n, err := wpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wpd *WasherProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(washerprofile.Table, sqlgraph.NewFieldSpec(washerprofile.FieldID, field.TypeUUID))
	if ps := wpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wpd.mutation.done = true
	return affected, err
}

// WasherProfileDeleteOne is the builder for deleting a single WasherProfile entity.
type WasherProfileDeleteOne struct {
	wpd *WasherProfileDelete
}

// Where appends a list predicates to the WasherProfileDelete builder.
func (wpdo *WasherProfileDeleteOne) Where(ps ...predicate.WasherProfile) *WasherProfileDeleteOne {
	wpdo.wpd.mutation.Where(ps...)
	return wpdo
}

// Exec executes the deletion query.
func (wpdo *WasherProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := wpdo.wpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{washerprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wpdo *WasherProfileDeleteOne) ExecX(ctx context.Context) {
	if err := wpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
